# Jekyll Configuration
exclude: ["Gemfile", "Gemfile.lock", "README.md"]

# Theme
remote_theme: pmarsceill/just-the-docs

# Theme configuration
title: Metadata 101 Schemas
description: Schema repository
search_enabled: false
aux_links:
    "GitHub":
      - "http://github.com/metadata101/schemas"
heading_anchors: false

# site configuration
defaults:
 - scope:
     path: "index.md"
   values:
     layout: "index"
 - scope:
     path: "*/index.md"
   values:
     layout: "index"
 - scope:
     path: "*/*/index.md"
   values:
     layout: "index"
 - scope:
     path: "*/*/*/index.md"
   values:
     layout: "index"
 - scope:
     path: "*/*/*/*/index.md"
   values:
     layout: "index"
 - scope:
     path: "*/*/*/*/*/index.md"
   values:
     layout: "index"